### ISSUE TITLE
module Mix.Release.Config.Providers.Elixir is not available

### ISSUE THREAD

**Issue by shopwith-eng** [bitwalker/distillery-aws-example#7]
Following this guide and running into this issue.

```
LifecycleEvent - ApplicationStart
Script - bin/migrate
[stderr]init terminating in do_boot ({,[{Elixir.Mix.Release.Config.Providers.Elixir,init,[[_]],[]},{Elixir.Mix.Releases.Config.Provider,-init/1-fun-0-,2,[{_},{_}]},{Elixir.Enum,-reduce/3-lists^foldl/2-0-,3,[{
[stderr]
[stderr]Crash dump is being written to: erl_crash.dump...done
[stdout]function Mix.Release.Config.Providers.Elixir.init/1 is undefined (module Mix.Release.Config.Providers.Elixir is not available)
[stdout] Mix.Release.Config.Providers.Elixir.init(["${RELEASE_ROOT_DIR}/etc/config.exs"])
[stdout] (distillery) lib/mix/lib/releases/config/provider.ex:45: anonymous fn/2 in Mix.Releases.Config.Provider.init/1
[stdout] (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
[stdout] (distillery) lib/mix/lib/releases/config/provider.ex:38: Mix.Releases.Config.Provider.init/1
[stdout] :init.eval_script/2
[stdout] :init.do_boot/3
[stdout]
[stdout]{"init terminating in do_boot",{#{'__exception__'=>true,'__struct__'=>'Elixir.UndefinedFunctionError',arity=>1,function=>init,message=>nil,module=>'Elixir.Mix.Release.Config.Providers.Elixir',reason=>nil},[{'Elixir.Mix.Release.Config.Providers.Elixir',init,[[<<"${RELEASE_ROOT_DIR}/etc/config.exs">>]],[]},{'Elixir.Mix.Releases.Config.Provider','-init/1-fun-0-',2,[{file,"lib/mix/lib/releases/config/provider.ex"},{line,45}]},{'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,[{file,"lib/enum.ex"},{line,1925}]},{'Elixir.Mix.Releases.Config.Provider',init,1,[{file,"lib/mix/lib/releases/config/provider.ex"},{line,38}]},{init,eval_script,2,[]},{init,do_boot,3,[]}]}}
[stdout]Unable to configure release!
```

Not sure what I'm doing wrong exactly :( I've tried both the migration setup in this repository and the updated one here: https://github.com/bitwalker/distillery/blob/master/docs/guides/running_migrations.md.

I did try to drop in the necessary files into an existing project so I'm wondering if I might have misconfigured something somewhere?

**Comment by shopwith-eng** [comment]
just a typo, sorry about that!
